src/main/java/ccti/pmbv/sistemas/blog/model/Pessoa.java
package ccti.pmbv.sistemas.blog.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.br.CNPJ;
import org.hibernate.validator.constraints.br.CPF;

import ccti.pmbv.sistemas.blog.model.validation.FisicaGroup;
import ccti.pmbv.sistemas.blog.model.validation.JuridicaGroup;

@Entity
@Table(name = "pessoa")
public class Pessoa implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@NotEmpty
	@Column(nullable = false, length = 100)
	private String nome;

	@NotNull
	@CNPJ(groups = JuridicaGroup.class)
	@CPF(groups = FisicaGroup.class)
	@Column(nullable = false, unique = true, length = 14)
	private String cpf;

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 10)
	private TipoPessoa tipo;
	
	@OneToOne(cascade = {CascadeType.ALL, CascadeType.PERSIST, CascadeType.REMOVE}, fetch = FetchType.EAGER, optional = false)    
	@JoinColumn(name = "usuario_id", unique = true, nullable = false, updatable = false)
	private Usuario usuario = new Usuario();
	
	@Lob
	@Column(name = "foto" , length = 1024000)
	private byte[] foto;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public TipoPessoa getTipo() {
		return tipo;
	}

	public void setTipo(TipoPessoa tipo) {
		this.tipo = tipo;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}	

	public byte[] getFoto() {
		return foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pessoa other = (Pessoa) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Transient
	public boolean isNovo() {
		return getId() == null;
	}

	@Transient
	public boolean isExistente() {
		return !isNovo();
	}
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return nome;
	}

}

src/main/java/ccti/pmbv/sistemas/blog/controller/CadastroPessoaBean.java
package ccti.pmbv.sistemas.blog.controller;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.nio.file.Files;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

import ccti.pmbv.sistemas.blog.exception.NegocioException;
import ccti.pmbv.sistemas.blog.model.Pessoa;
import ccti.pmbv.sistemas.blog.model.TipoPessoa;
import ccti.pmbv.sistemas.blog.service.PessoaService;
import ccti.pmbv.sistemas.blog.service.FileUploadService;
import ccti.pmbv.sistemas.blog.service.UsuarioService;
import ccti.pmbv.sistemas.blog.util.jsf.FacesUtil;

@Named("cadastroClienteBean")
@ViewScoped
public class CadastroPessoaBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private StreamedContent streamedContent;

	private UploadedFile uploadedFile;
	
	private Pessoa pessoa;

	@Inject
	private FileUploadService uploadService;
	
	@Inject
	private PessoaService pessoaService;

	@Inject
	private UsuarioService usuarioService;

	public void inicializar() {
		if (pessoa == null) {
			limpar();
		}
	}

	public void limpar() {
		this.pessoa = new Pessoa();
		this.pessoa.setTipo(TipoPessoa.FISICA);

	}

	public void salvar() {

		try {
			boolean isClienteExistente = usuarioService.verificarUsuarioExistente(pessoa.getUsuario());
			
			if (pessoa.isNovo() && isClienteExistente) {
				throw new NegocioException("Já existe um usuário com o e-mail informado.");
			}
							
			pessoaService.salvar(pessoa);
			FacesUtil.addInfoMessage("Pessoa salvo com sucesso!");
			limpar();
		} catch (NegocioException e) {
			FacesUtil.addErrorMessage(e.getMessage());
		}

	}

	// https://javabydeveloper.com/save-image-working-large-objects/
	public void upload(FileUploadEvent event) {		
		try {
			
			UploadedFile uploadedFile = event.getFile();
			
			uploadService.escrever(uploadedFile.getFileName(), uploadedFile.getContents());									 				
			
//			byte[] picInBytes = new byte[(int) arquivo.length()];
//			FileInputStream fileInputStream = new FileInputStream(arquivo);
//			fileInputStream.read(picInBytes);
//			fileInputStream.close();
			pessoa.setFoto(uploadedFile.getContents());						
			FacesUtil.addInfoMessage("Upload da foto completo.");
		} catch (IOException e) {
			FacesUtil.addErrorMessage("Erro ao fazer upload da foto.");
		}
	}
	
	public void download(File file) throws IOException {

		InputStream inputStream = new FileInputStream(file);

		streamedContent = new DefaultStreamedContent(inputStream, Files.probeContentType(file.toPath()),
				file.getName());
	}

	public StreamedContent getStreamedContent() {
		return streamedContent;
	}		

	public UploadedFile getUploadedFile() {
		return uploadedFile;
	}

	public void setUploadedFile(UploadedFile uploadedFile) {
		this.uploadedFile = uploadedFile;
	}

	public Pessoa getPessoa() {
		return pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public boolean isEditando() {
		return pessoa.getId() != null;
	}

}

src/main/webapp/paginas/cliente/CadastroCliente.xhtml
<ui:composition template="/WEB-INF/template/Layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui">

	<ui:define name="titulo">#{cadastroClienteBean.editando ? 'Edição de cliente' : 'Novo cliente'}</ui:define>

	<ui:define name="content">

		<f:metadata>
			<o:viewParam name="cliente" value="#{cadastroClienteBean.pessoa}" />
			<f:viewAction action="#{cadastroClienteBean.inicializar}" />
		</f:metadata>

		<h:form id="frm" enctype="multipart/form-data">

			<p:focus context="frm" />

			<h1 class="aw-page-title">#{cadastroClienteBean.editando ?
				'Edição de cliente' : 'Novo cliente'}</h1>

			<p:messages id="messages" autoUpdate="true" closable="true" />

			<p:toolbar>
				<p:toolbarGroup>
					<p:button value="Novo" outcome="/paginas/cliente/CadastroCliente" />
					<p:commandButton value="Salvar" id="botaoSalvar"
						action="#{cadastroClienteBean.salvar()}" process="@form"
						update="@form" validateClient="true" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Pesquisa"
						outcome="/paginas/cliente/PesquisaCliente" />
				</p:toolbarGroup>
			</p:toolbar>

			<div class="ui-fluid">
				<p:panelGrid columns="2" id="panel" style="margin-top: 20px; width: 100%" layout="grid"
					columnClasses="ui-grid-col-1,ui-grid-col-12">
					<p:outputLabel value="Nome" for="nome" />
					<p:inputText type="text" id="nome" size="60" maxlength="80"
						value="#{cadastroClienteBean.pessoa.nome}" />

					<p:outputLabel value="CPF" for="cpf" />
					<p:inputMask id="cpf" size="14" maxlength="14" autoClear="false"
						mask="#{cadastroClienteBean.pessoa.tipo.mascara}"
						disabled="#{cadastroClienteBean.editando}" converter="cpfCnpjMask"
						value="#{cadastroClienteBean.pessoa.cpf}">
						<f:validateBean
							validationGroups="#{cadastroClienteBean.pessoa.tipo.grupoValidacao}" />
					</p:inputMask>

					<p:outputLabel value="E-mail" for="email" />
					<p:inputText type="email" id="email"
						disabled="#{cadastroClienteBean.pessoa.existente}"
						value="#{cadastroClienteBean.pessoa.usuario.email}" />

					<p:outputLabel value="Senha" for="senha" />
					<p:password id="senha" match="confirmasenha" feedback="false"
						weakLabel="Fraca" goodLabel="Boa" strongLabel="Ótima"
						validatorMessage="Erro: Senhas não conferem!"
						promptLabel="Digite a senha" placeholder="Digite a senha"
						inline="false" redisplay="#{cadastroClienteBean.pessoa.novo}"
						value="#{cadastroClienteBean.pessoa.usuario.senha}"
						title="Informe a senha" maxlength="15" size="40" required="false" />

					<p:outputLabel value="Confirme a senha" for="confirmasenha" />
					<p:password id="confirmasenha" maxlength="15" size="40"
						title="Confirme a senha" feedback="false" weakLabel="Fraca"
						goodLabel="Boa" strongLabel="Ótima"
						placeholder="Digite a senha novamente"
						promptLabel="Confirme a senha" inline="false" required="false" />

					<p:outputLabel for="fileUpload" />
					<h:panelGroup>
						<p:fileUpload value="#{cadastroClienteBean.uploadedFile}"  
							label="Escolher" id="fileUpload" mode="advanced" skinSimple="true"
							auto="false" uploadLabel="Enviar" cancelLabel="Cancelar" sizeLimit="1024000"
							fileUploadListener="#{cadastroClienteBean.upload}"
							update="fotoPanelGroup" />
						<p:commandButton value="Enviar" ajax="false" update="@none"
							actionListener="#{cadastroClienteBean.upload}" rendered="false" />
						<h:panelGrid id="fotoPanelGroup">
							<p:graphicImage url="/arquivo-servlet?nome=#{cadastroClienteBean.pessoa.cpf}"
								rendered="#{cadastroClienteBean.pessoa.foto ne null}"
								width="200px" id="foto" />
						</h:panelGrid>
					</h:panelGroup>


				</p:panelGrid>
			</div>

		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/paginas/cliente/PesquisaCliente.xhtml
<ui:composition template="/WEB-INF/template/Layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="titulo">Pesquisa de cliente</ui:define>

	<ui:define name="content">

		<h:form id="frmPesquisa">

			<h1 class="aw-page-title">Pesquisa de cliente</h1>

			<p:messages id="messages" autoUpdate="true" closable="true" />

			<p:toolbar style="margin-top: 20px">
				<p:toolbarGroup>
					<p:commandButton value="Pesquisar"
						action="#{pesquisaClientesBean.pesquisar}" update="@form" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Novo" outcome="/paginas/cliente/CadastroCliente" />
				</p:toolbarGroup>
			</p:toolbar>

			<div class="ui-fluid">
				<p:panelGrid columns="2" id="painel" layout="grid"
					style="width: 100%; margin-top: 20px"
					columnClasses="ui-grid-col-1,ui-grid-col-12">
					<p:outputLabel value="CPF" for="cpf" />
					<p:inputText id="cpf" size="20"
						value="#{pesquisaClientesBean.filtro.cpf}" />

					<p:outputLabel value="Nome" for="nome" />
					<p:inputText id="nome" size="60"
						value="#{pesquisaClientesBean.filtro.nome}" />
				</p:panelGrid>
			</div>
			<p:dataTable id="clientesTable" styleClass="ui-corner-all"
				resizableColumns="true"
				value="#{pesquisaClientesBean.pessoasFiltrados}" var="_cliente"
				style="margin-top: 20px" emptyMessage="Nenhum cliente encontrado."
				lazy="true" rows="20" paginator="true" draggableRows="true"
				paginatorAlwaysVisible="false" reflow="true" liveResize="true"
				paginatorPosition="bottom" rowHover="true" rowKey="#{_cliente.id}"
				rowSelectMode="checkbox">

				<p:column width="100">
					<p:graphicImage styleClass="rounded-corner"
						url="/arquivo-servlet?nome=#{_cliente.cpf}" style=""
						rendered="#{_cliente.foto ne null}" width="80px" id="foto" />
				</p:column>

				<p:column headerText="CPF">
					<h:outputText value="#{_cliente.cpf}" converter="cpfCnpjMask" />
				</p:column>

				<p:column headerText="Nome">
					<h:outputText value="#{_cliente.nome}" />
				</p:column>

				<p:column headerText="E-mail">
					<h:outputText value="#{_cliente.usuario.email}" />
				</p:column>

				<p:column headerText="Tipo">
					<h:outputText value="PESSOA #{_cliente.tipo}" converter="cpfCnpjMask" />
				</p:column>

				<p:column width="100" style="text-align: center">
					<p:button outcome="/paginas/cliente/CadastroCliente"
						icon="ui-icon-pencil" title="Editar">
						<f:param name="cliente" value="#{_cliente.id}" />
					</p:button>
					<p:commandButton icon="ui-icon-trash" title="Excluir"
						oncomplete="PF('confirmacaoExclusao').show()" process="@this"
						update=":frmPesquisa:confirmacaoExclusaoDialog">
						<f:setPropertyActionListener
							target="#{pesquisaClientesBean.pessoaSelecionado}"
							value="#{_cliente}" />
					</p:commandButton>
				</p:column>

			</p:dataTable>

			<p:confirmDialog header="Exclusão de cliente" closeOnEscape="true" width="340" responsive="true"
				message="Tem certeza que deseja excluir o cliente #{pesquisaClientesBean.pessoaSelecionado.nome}?"
				widgetVar="confirmacaoExclusao" id="confirmacaoExclusaoDialog">

				<p:commandButton value="Sim"
					oncomplete="PF('confirmacaoExclusao').hide();"
					action="#{pesquisaClientesBean.excluir}" process="@this"
					update=":frmPesquisa:clientesTable" id="yesButton" />
				<p:button value="Não"
					onclick="PF('confirmacaoExclusao').hide(); return false;" />
			</p:confirmDialog>
		</h:form>
	</ui:define>
</ui:composition>